#pragma once

#include <AnimalSerializer.h>
#include <ArmourTypeSerializer.h>
#include <AttackTableSerializer.h>
#include <BookSerializer.h>
#include <ClimateSerializer.h>
#include <CreaturePaceSerializer.h>
#include <CultureSerializer.h>
#include <CultureTypeSerializer.h>
#include <DiseaseSerializer.h>
#include <DiseaseTypeSerializer.h>
#include <FixedTableCreator.h>
#include <LanguageCategorySerializer.h>
#include <LanguageSerializer.h>
#include <PersistentCache.h>
#include <PersistentObjectFileSerializer.h>
#include <PersistentObjectManager.h>
#include <PoisonSerializer.h>
#include <PoisonTypeSerializer.h>
#include <ProfessionDatafileParserXml.h>
#include <ProfessionSerializer.h>
#include <RaceSerializer.h>
#include <SkillCategorySerializer.h>
#include <SkillGroupSerializer.h>
#include <SkillProgressionTypeSerializer.h>
#include <SkillSerializer.h>
#include <SpecialAttackTableSerializer.h>
#include <SpellListSerializer.h>
#include <TrainingPackageCostTableFileSerializer.h>
#include <TrainingPackageSerializer.h>
#include <TreasureCodeSerializer.h>
#include <WeaponTypeSerializer.h>
