#pragma once

#include <AnimalData.h>
#include <ArmourTypeData.h>
#include <table/AttackTable.h>
#include <BookData.h>
#include <CreaturePaceData.h>
#include <CultureData.h>
#include <CultureTypeData.h>
#include <DiseaseData.h>
#include <DiseaseTypeData.h>
#include <ForagableData.h>
#include <LanguageData.h>
#include <LanguageCategoryData.h>
#include <PoisonData.h>
#include <PoisonTypeData.h>
#include <ProfessionData.h>
#include <RaceData.h>
#include <SkillCategoryData.h>
#include <SkillData.h>
#include <SkillGroupData.h>
#include <SkillProgressionTypeData.h>
#include <table/SpecialAttackTable.h>
#include <SpellListData.h>
#include <table/TrainingPackageCostTable.h>
#include <TrainingPackageData.h>
#include <TreasureCodeData.h>
#include <WeaponTypeData.h>
